name: Mobile Build
run-name: ${{ github.event.inputs.build_name }}

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
    
      build_name:
        description: Build Name
        required: true
        default: Mobile Build
        
      android_flags:
        description: Android Flags
        required: false
        default:
        
      ios_flags:
        description: Ios Flags
        required: false
        default: -nosign
        
      platform:
        description: "Build platform"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - android
          - ios
          
      rebuild_cache:
        description: "Rebuild Cache?"
        required: true
        default: "No"
        type: choice
        options:
          - "Yes"
          - "No"
          
jobs:
  buildAndroid:
    if: ${{ github.event_name == 'push' || github.event.inputs.platform == 'android' || github.event.inputs.platform == 'all' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - uses: actions/setup-java@v4
        with:
         distribution: temurin
         java-version: '17'

      - name: Restore cache
        if: ${{ github.event_name == 'push' || github.event.inputs.rebuild_cache != 'Yes' || github.event_name == 'push'}}
        uses: actions/cache/restore@v4
        with:
         path: |
          ~/.haxelib
          ~/.lime
          ~/.openfl
          ~/.gradle/wrapper
          ~/Android/Sdk
          /home/runner/hxcpp_cache
         key: android-cache-${{ runner.os }}
         restore-keys: |
          android-cache-${{ runner.os }}-

      - name: Delete OpenFL
        run: rm -rf ~/.haxelib/openfl

      - name: Setup environment
        run: |
         mkdir -p /home/runner/hxcpp_cache
         echo '<xml>
          <set name="HXCPP_COMPILE_CACHE" value="/home/runner/hxcpp_cache" />
          <set name="HXCPP_CACHE_MB" value="4096" />
         </xml>' > ~/.hxcpp_config.xml
          haxelib setup ~/haxelib

          haxe -cp commandline -D analyzer-optimize --run Main setup --silent
          
          printf "%s\n%s\n%s\n" \
            "$ANDROID_HOME" \
            "$ANDROID_NDK_ROOT" \
            "$JAVA_HOME" \
            | haxelib run lime setup android  
          
          haxelib list

      - name: Install neccessary android tools
        run: |
          mkdir -p ~/android-sdk
          cd ~/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-*.zip

          mkdir cmdline-tools/latest
          mv cmdline-tools/* cmdline-tools/latest/ || true

          yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          ~/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "ndk;29.0.14206865"

          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$HOME/android-sdk/ndk/29.0.14206865" >> $GITHUB_ENV

      - name: Setup Android
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.jvmargs=-Xmx5g -XX:MaxMetaspaceSize=1536m -Dfile.encoding=UTF-8" > ~/.gradle/gradle.properties
          echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
          echo "org.gradle.parallel=false" >> ~/.gradle/gradle.properties
          echo "org.gradle.configureondemand=false" >> ~/.gradle/gradle.properties
          echo "android.splits.abi.enable=false" >> ~/.gradle/gradle.properties
          echo "JAVA_TOOL_OPTIONS=-Xmx5g" >> $GITHUB_ENV
          echo "${{ secrets.KEYSTORE }}" | base64 -d > keystore.jks

      - name: Patch Lime
        run: |
         FILE=".haxelib/openfl/git/src/openfl/net/FileReference.hx"

         if [ -f "$FILE" ]; then
           echo "Applying conditional patch..."
  
           sed -i 's/lime\.ui\.FileDialogFilter/lime.ui.FileDialog/g' "$FILE'

          if grep -q "FileDialogFilter" "$FILE"; then
             echo "WARNING: unresolved references remain"
             exit 1
           fi
         fi
         
      - name: Build APK
        run: |
         haxelib run lime clean android
         haxelib run lime build android -final -release \
           --certificate-path="keystore.jks" \
           --certificate-alias="${{ secrets.KEYSTORE_ALIAS }}" \
           --certificate-password="${{ secrets.KEYSTORE_PASSWORD }}" \
           --certificate-alias-password="${{ secrets.KEY_PASSWORD }}" \
           -clean ${{ github.event.inputs.android_flags }}
         find . -name "*.apk"

      - name: Inspect openfl
        if: failure()
        run: |
         grep -n "hello" .haxelib/openfl/git/src/openfl/display3D/Context3D.hx
         grep -n "__clear" .haxelib/openfl/git/src/openfl/display3D/Context3D.hx

      - name: debug
        run: |
         #find . -name "AndroidManifest.xml"
         cat export/release/android/bin/app/src/main/AndroidManifest.xml
         
      - name: Save cache
        if: ${{ success() && (github.event_name == 'push' || github.event.inputs.rebuild_cache != 'Yes' || github.event_name == 'push') }}
        uses: actions/cache/save@v4
        with:
         path: |
          ~/.haxelib
          ~/.lime
          ~/.openfl
          ~/.gradle/wrapper
          ~/Android/Sdk
          /home/runner/hxcpp_cache
         key: android-cache-${{ runner.os }}

      - uses: actions/upload-artifact@v4
        with:
          name: Android-Release
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk

  buildiOS:
    if: ${{ github.event_name == 'push' || github.event.inputs.platform == 'ios' || github.event.inputs.platform == 'all' }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7
          architecture: arm64

      - name: Restore cache
        if: ${{ github.event_name == 'push' || github.event.inputs.rebuild_cache != 'Yes' || github.event_name == 'push'}}
        uses: actions/cache/restore@v4
        with:
         path: |
          ~/haxelib
          ~/.lime
          ~/.openfl
          ~/hxcpp_cache
          ~/Library/Developer/Xcode/DerivedData
          export/ios/build
         key: ios-cache-${{ runner.os }}-${{ hashFiles('**/project.xml') }}
         restore-keys: |
          ios-cache-${{ runner.os }}-

      - name: Setup environment
        run: |
          haxelib setup ~/haxelib
          
          haxe -cp commandline -D analyzer-optimize --run Main setup --silent

          echo "n" | haxelib run lime setup ios
          
      - name: Clean iOS
        run: haxelib run lime clean ios

      - name: Build iOS
        run: |
          #arch -x86_64 
          haxelib run lime build ios ${{ github.event.inputs.ios_flags }}
          find . -name "*.ipa"
           
      - name: Compile Xcode Project
        run: |
          xcodebuild \
           -project export/release/ios/CodenameEngine.xcodeproj \
           -scheme CodenameEngine \
           -configuration Release \
           -sdk iphoneos \
           -derivedDataPath $PWD/build \
           CODE_SIGNING_ALLOWED=NO \
           CODE_SIGNING_REQUIRED=NO \
           CODE_SIGN_IDENTITY="" \
           build

      - name: Export Ipa
        run: |
          mkdir -p Payload
          
          cp -r $PWD/build/Build/Products/Release-iphoneos/CodenameEngine.app Payload/
          
          mkdir -p outputs/ipa/debug
          zip -qr outputs/ipa/debug/CodenameEngine-debug.ipa Payload

      - name: Save cache
        if: ${{ success() && (github.event_name == 'push' || github.event.inputs.rebuild_cache != 'Yes' || github.event_name == 'push') }}
        uses: actions/cache/save@v4
        with:
         path: |
          ~/hxcpp_cache
          export/ios
         key: ios-cache-${{ runner.os }}-${{ hashFiles('**/project.xml') }}
          
      - uses: actions/upload-artifact@v4
        with:
          name: iosBuild
          path: outputs/ipa/debug/*
          if-no-files-found: ignore
